### PR TITLE
Chat model

### PR DESCRIPTION
**Pull request by ahmedcharfeddine013**
In this model i made a chat schema to work on?

### CODE REVIEW

**Comment by prechy123** [comment]
Nice work bro, but will this be real time?

**Comment by ahmedcharfeddine013** [comment]
it will be. It's just i'm trying to make the backend and as i'm a frontend developer with not a lot of experience in backend i'm trying my best to provide the best, so excuse my bad code in the backend mate :)
________________________________

**Comment by prechy123** [comment]
The backwnd code is fine, do you know how to implement socket io,
Are you on discord

**Comment by yoshi-1012** [comment]
Remove all the extra files from your PR.
Only have the files that need to be changed in your PR.

**Comment by yoshi-1012** [comment]
Do you have any contact methods?
Email?
Discord?

**Comment by yoshi-1012** [comment]
Use a .gitignore file

**Comment by ahmedcharfeddine013** [comment]
okay sure i'll do it.
________________________________

**Review by prechy123 — APPROVED** [review]

**Review by prechy123 — APPROVED** [review]

**Comment by yoshi-1012** [comment]
You didn't remove the extra files yet that don't need to be in the PR.
I think "Files Changed" should not be 254.

**Comment by ahmedcharfeddine013** [comment]
You are right. ill do it as soon as possible.

**Comment by prechy123** [comment]
You can remove with this
```
git rm -r --cached node_modules
```
then 
```
git commit -m "Remove node_modules"
```
then push

**Comment by prechy123** [comment]
There was a conflict in frontend/src/components/signin
but do this first

**Comment by ahmedcharfeddine013** [comment]
Done.

**Pull request merged**
